;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright (c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3255-7514-28			    |
; |			    Giancarlo Russo, HT Srl			    |
; +-------------------------------------------------------------------------+
;
; Input MD5   : FC62D7EAAC5580382B47CDBFBE85A0C3
; Input CRC32 : 676887D2

; ---------------------------------------------------------------------------
; File Name   : C:\Users\sphere\Desktop\Function_1.bin
; Format      : Binary file
; Base Address: 0000h Range: 495E8A0h - 495E92Bh Loaded length: 008Bh
; ===========================================================================
;int Function_1(char* str)
Function_1:
		mov	ecx, [esp+4]
		test	ecx, 3
		jz	short loc_495E8D0

loc_495E8AC:				; CODE XREF: seg000:0495E8BBj
		mov	al, [ecx]
		add	ecx, 1
		test	al, al
		jz	short loc_495E903
		test	ecx, 3
		jnz	short loc_495E8AC
		add	eax, 0
		lea	esp, [esp+0]
		lea	esp, [esp+0]

loc_495E8D0:				; CODE XREF: seg000:0495E8AAj
					; seg000:0495E8E6j ...
		mov	eax, [ecx]
		mov	edx, 7EFEFEFFh
		add	edx, eax
		xor	eax, 0FFFFFFFFh
		xor	eax, edx
		add	ecx, 4
		test	eax, 81010100h
		jz	short loc_495E8D0
		mov	eax, [ecx-4]
		test	al, al
		jz	short loc_495E921
		test	ah, ah
		jz	short loc_495E917
		test	eax, 0FF0000h
		jz	short loc_495E90D
		test	eax, 0FF000000h
		jz	short loc_495E903
		jmp	short loc_495E8D0
; ---------------------------------------------------------------------------

loc_495E903:				; CODE XREF: seg000:0495E8B3j
					; seg000:0495E8FFj
		lea	eax, [ecx-1]
		mov	ecx, [esp+4]
		sub	eax, ecx
		retn
; ---------------------------------------------------------------------------

loc_495E90D:				; CODE XREF: seg000:0495E8F8j
		lea	eax, [ecx-2]
		mov	ecx, [esp+4]
		sub	eax, ecx
		retn
; ---------------------------------------------------------------------------

loc_495E917:				; CODE XREF: seg000:0495E8F1j
		lea	eax, [ecx-3]
		mov	ecx, [esp+4]
		sub	eax, ecx
		retn
; ---------------------------------------------------------------------------

loc_495E921:				; CODE XREF: seg000:0495E8EDj
		lea	eax, [ecx-4]
		mov	ecx, [esp+4]
		sub	eax, ecx
		retn
		align 10h