;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3255-7514-28			    |
; |			    Giancarlo Russo, HT	Srl			    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	1D79887C7C4D2AB142C14AAA3A44D2D0
; Input	CRC32 :	48EDEBAA

; ---------------------------------------------------------------------------
; File Name   :	C:\Users\sphere\Desktop\SerialChecker.bin
; Format      :	Binary file
; Base Address:	0000h Range: 48C5380h -	48C5BA1h Loaded	length:	0821h
; ===========================================================================
;int SerialChecker(char* username, char* serial, void* unknown_1, int unknown_2)
SerialChecker:
		push	ebp
		mov	ebp, esp
		push	0FFFFFFFFh
		push	498FA8Ah
		mov	eax, [fs:0]
		push	eax
		sub	esp, 188h
		;========================
		;Stack protector
		;mov	eax, [ds:49D8724h]
		;xor	eax, ebp
		;mov	[ebp-18h], eax
		;========================
		push	eax
		lea	eax, [ebp-0Ch]
		mov	 [fs:0], eax
		mov	eax, [ebp+8]
		push	eax
		call	near  Function_1
		add	esp, 4
		test	eax, eax
		jz	loc_48C5537
		mov	ecx, [ebp+0Ch]
		push	ecx
		call	near  Function_1
		add	esp, 4
		test	eax, eax
		jnz	loc_48C5537
		mov	ecx, 49DB658h
		call	near  4872740h
		and	eax, 2
		jz	loc_48C5537
		push	20000h
		call	near  4947D31h
		add	esp, 4
		mov	[ebp-12Ch], eax
		mov	edx, [ebp-12Ch]
		mov	[ebp-14h], edx
		mov	dword  [ebp-4], 0
		xor	eax, eax
		shl	eax, 1
		xor	ecx, ecx
		mov	edx, [ebp-14h]
		mov	[edx+eax], cx
		mov	eax, [ebp+8]
		push	eax
		lea	ecx, [ebp-11Ch]
		push	ecx
		call	near  494E930h
		add	esp, 8
		mov	dword  [ebp-10h], 0
		mov	edx, [ebp-14h]
		mov	[ebp-13Ch], edx
		lea	eax, [ebp-10h]
		push	eax
		mov	ecx, [ebp-13Ch]
		push	ecx
		mov	edx, [ebp+0Ch]
		push	edx
		mov	eax, [ebp+8]
		push	eax
		lea	ecx, [ebp-11Ch]
		push	ecx
		mov	ecx, [ds:49DD540h]
		call	near  4879530h
		xor	edx, edx
		shl	edx, 1
		mov	eax, [ebp-14h]
		movzx	ecx, word  [eax+edx]
		test	ecx, ecx
		jz	loc_48C550C
		mov	edx, [ebp-14h]
		mov	[ebp-140h], edx
		push	10h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	eax, [ebp-140h]
		push	eax
		mov	ecx, [ebp+10h]
		push	ecx
		push	49A3E60h
		call	near  493A7C0h
		add	esp, 14h
		mov	dword  [ebp-130h], 0
		mov	dword  [ebp-4], 0FFFFFFFFh
		mov	edx, [ebp-14h]
		mov	[ebp-148h], edx
		mov	eax, [ebp-148h]
		mov	[ebp-144h], eax
		mov	ecx, [ebp-144h]
		push	ecx
		call	near  494E864h
		add	esp, 4
		mov	eax, [ebp-130h]
		jmp	loc_48C5B88
; ---------------------------------------------------------------------------

loc_48C550C:				; CODE XREF: seg000:048C546Bj
		mov	dword  [ebp-4], 0FFFFFFFFh
		mov	edx, [ebp-14h]
		mov	[ebp-150h], edx
		mov	eax, [ebp-150h]
		mov	[ebp-14Ch], eax
		mov	ecx, [ebp-14Ch]
		push	ecx
		call	near  494E864h
		add	esp, 4

loc_48C5537:				; CODE XREF: seg000:048C53B9j
					; seg000:048C53CDj ...
		mov	edx, [ebp+0Ch]
		push	edx
		call	near  Function_1
		add	esp, 4
		test	eax, eax
		jnz	loc_48C55D5
		push	10h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	1Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	eax, [ebp+10h]
		push	eax
		push	49A3E4Ch
		call	near  493A7C0h
		add	esp, 14h
		xor	eax, eax
		jmp	loc_48C5B88
; ---------------------------------------------------------------------------

loc_48C55D5:				; CODE XREF: seg000:048C5545j
		mov	ecx, [ds_49A3C1Ch]
		mov	[ebp-15Ch], ecx
		sub	esp, 8
		mov	edx, esp
		mov	[ebp-154h], esp
		mov	[ebp-158h], edx
		mov	eax, [ebp-158h]
		mov	byte  [eax],	0
		mov	dword  [ebp-4], 1
		mov	dword  [ebp-4], 0FFFFFFFFh
		mov	ecx, [ebp-158h]
		mov	[ebp-18Ch], ecx
		mov	dword  [ebp-4], 2
		push	1
		mov	edx, [ebp+0Ch]
		push	edx
		mov	eax, [ebp+8]
		push	eax
		mov	dword  [ebp-4], 0FFFFFFFFh
		mov	ecx, object_1 ;49DAFB0h
		call	near  487EDD0h
		mov	[ebp-18Dh], al
		movzx	ecx, byte  [ebp-18Dh]
		test	ecx, ecx
		jnz	loc_48C5AB3
		call	near  48C2450h
		mov	[ebp-128h], eax
		push	0
		push	0
		lea	edx, [ebp-124h]
		push	edx
		call	near  487DBF0h
		add	esp, 0Ch
		mov	dword  [ebp-4], 3
		mov	eax, [ds_49A3C1Ch]
		mov	[ebp-164h], eax
		sub	esp, 8
		mov	ecx, esp
		mov	[ebp-134h], esp
		mov	[ebp-160h], ecx
		mov	edx, [ebp-160h]
		mov	byte  [edx],	0
		mov	byte  [ebp-4], 4
		mov	byte  [ebp-4], 3
		mov	eax, [ebp-160h]
		mov	[ebp-194h], eax
		mov	byte  [ebp-4], 5
		mov	ecx, [ebp-124h]
		mov	[ebp-168h], ecx
		mov	edx, [ebp+0Ch]
		push	edx
		mov	eax, [ebp+8]
		push	eax
		mov	byte  [ebp-4], 3
		mov	ecx, [ebp-168h]
		call	near  48753F0h
		cmp	dword  [ebp-128h], 52Fh
		jnz	short loc_48C5737
		mov	ecx, [ebp-124h]
		mov	[ebp-16Ch], ecx
		push	0
		mov	ecx, [ebp-16Ch]
		call	near  4879900h
		movzx	edx, al
		test	edx, edx
		jz	short loc_48C5737
		mov	eax, [ebp-124h]
		mov	[ebp-170h], eax
		mov	ecx, [ebp-170h]
		mov	dl, [ecx+604h]
		mov	[ebp-171h], dl
		movzx	eax, byte  [ebp-171h]
		test	eax, eax
		jz	short loc_48C5737
		push	0
		push	2
		call	near  48C2720h
		add	esp, 8
		jmp	loc_48C5A58
; ---------------------------------------------------------------------------

loc_48C5737:				; CODE XREF: seg000:048C56DBj
					; seg000:048C56FBj ...
		cmp	dword  [ebp-128h], 52Fh
		jnz	loc_48C57F5
		mov	ecx, [ebp-124h]
		mov	[ebp-178h], ecx
		mov	edx, [ebp-178h]
		mov	eax, [edx+560h]
		mov	[ebp-17Ch], eax
		cmp	dword  [ebp-17Ch], 0
		jz	loc_48C57F5
		mov	ecx, [ebp-124h]
		mov	[ebp-180h], ecx
		mov	edx, [ebp-180h]
		mov	eax, [edx+560h]
		mov	[ebp-184h], eax
		push	10010h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	0
		mov	ecx, [ebp-184h]
		push	ecx
		call	near  488F170h
		add	esp, 8
		push	eax
		mov	edx, [ebp+10h]
		push	edx
		push	49A3E30h
		call	near  493A7C0h
		add	esp, 14h
		jmp	loc_48C5A58
; ---------------------------------------------------------------------------

loc_48C57F5:				; CODE XREF: seg000:048C5741j
					; seg000:048C576Cj
		cmp	dword  [ebp-128h], 533h
		jnz	loc_48C5890
		push	10010h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	21h
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	eax, [ebp+10h]
		push	eax
		push	49A3E18h
		call	near  493A7C0h
		add	esp, 14h
		jmp	loc_48C5A58
; ---------------------------------------------------------------------------

loc_48C5890:				; CODE XREF: seg000:048C57FFj
		cmp	dword  [ebp-128h], 701h
		jnz	loc_48C592B
		push	10010h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	18h
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	ecx, [ebp+10h]
		push	ecx
		push	49A3E04h
		call	near  493A7C0h
		add	esp, 14h
		jmp	loc_48C5A58
; ---------------------------------------------------------------------------

loc_48C592B:				; CODE XREF: seg000:048C589Aj
		cmp	dword  [ebp-128h], 3F5h
		jz	short loc_48C5947
		cmp	dword  [ebp-128h], 55Dh
		jnz	loc_48C59D2

loc_48C5947:				; CODE XREF: seg000:048C5935j
		push	10010h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	51h
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	edx, [ebp+10h]
		push	edx
		push	49A3DECh
		call	near  493A7C0h
		add	esp, 14h
		jmp	loc_48C5A58
; ---------------------------------------------------------------------------

loc_48C59D2:				; CODE XREF: seg000:048C5941j
		push	10010h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	0Fh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	1Ch
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	eax, [ebp+10h]
		push	eax
		push	49A3CA8h
		call	near  493A7C0h
		add	esp, 14h

loc_48C5A58:				; CODE XREF: seg000:048C5732j
					; seg000:048C57F0j ...
		mov	ecx, [ebp-128h]
		push	ecx
		call	near  48C2440h
		add	esp, 4
		mov	dword  [ebp-138h], 0
		mov	dword  [ebp-4], 6
		mov	dword  [ebp-4], 0FFFFFFFFh
		lea	edx, [ebp-120h]
		mov	[ebp-188h], edx
		mov	eax, [ebp-188h]
		cmp	dword  [eax], 0
		jz	short loc_48C5AA3
		mov	ecx, [ebp-188h]
		mov	ecx, [ecx]
		call	near  4821940h

loc_48C5AA3:				; CODE XREF: seg000:048C5A94j
		mov	eax, [ebp-138h]
		jmp	loc_48C5B88
; ---------------------------------------------------------------------------
		jmp	loc_48C5B83
; ---------------------------------------------------------------------------

loc_48C5AB3:				; CODE XREF: seg000:048C5646j
		movzx	edx, byte  [ebp+14h]
		test	edx, edx
		jnz	loc_48C5B83
		push	10040h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	1Bh
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	49E57B0h
		push	1Ah
		call	near  488EBF0h
		add	esp, 28h
		push	eax
		mov	eax, [ebp+10h]
		push	eax
		push	49A3C94h
		call	near  493A7C0h
		add	esp, 14h
		mov	ecx, 1
		test	ecx, ecx
		jz	short loc_48C5B5F
		mov	edx, [ds:49DB658h]
		or	edx, 8
		mov	[ds:49DB658h], edx
		jmp	short loc_48C5B71
; ---------------------------------------------------------------------------

loc_48C5B5F:				; CODE XREF: seg000:048C5B4Cj
		mov	eax, 8
		not	eax
		and	eax, [ds:49DB658h]
		mov	[ds:49DB658h], eax

loc_48C5B71:				; CODE XREF: seg000:048C5B5Dj
		mov	ecx, [ds:49DB65Ch]
		or	ecx, 80h
		mov	[ds:49DB65Ch], ecx

loc_48C5B83:				; CODE XREF: seg000:048C5AAEj
					; seg000:048C5AB9j
		mov	eax, 1

loc_48C5B88:				; CODE XREF: seg000:048C5507j
					; seg000:048C55D0j ...
		mov	ecx, [ebp-0Ch]
		mov	 [fs:0], ecx
		pop	ecx
		mov	ecx, [ebp-18h]
		xor	ecx, ebp
		call	near  494C68Ah
		mov	esp, ebp
		pop	ebp
		retn
		align 10h